#!/bin/bash

MARCEL_HOME=/home/jao/git/marcel/src
MARCEL_MAIN=$MARCEL_HOME/marcel/main.py
PYTHONPATH=$MARCEL_HOME

function suppress_interruptions()
{
  return 0
}

trap suppress_interruptions SIGINT
trap suppress_interruptions SIGTSTP

python3 $MARCEL_MAIN
