#!/bin/bash

export NEWEST_LAYOUT=ws3

export TEST_DIR=/home/jao/git/marcel/test/system/test_migration
export TEST_HOME=/tmp/test_home
export TEST_ARTIFACTS=/tmp/test_artifacts
export CURRENT_LAYOUT=$TEST_DIR/$NEWEST_LAYOUT
export XDG_CONFIG_HOME=$TEST_HOME/.config
export XDG_DATA_HOME=$TEST_HOME/.local/share

FAILURES=$((0))

initialize() {
  sudo rm -rf $TEST_ARTIFACTS
  mkdir -p $TEST_ARTIFACTS
}

check() {
  diff_file=$1"_to_"$NEWEST_LAYOUT".diff"
  diff $TEST_ARTIFACTS/expected.$1 $TEST_ARTIFACTS/actual.$1 > /$TEST_ARTIFACTS/$diff_file
  if [ $? != '0' ]; then
    FAILURES=$(($FAILURES+1))
    echo "Error on $diff_file"
  fi
}

test_migration() {
  old_layout=$1
  sudo rm -rf $TEST_HOME >& /dev/null
  cp -rp $TEST_DIR/$old_layout $TEST_HOME
  marcel <<EOF
EOF
  pushd $TEST_HOME >& /dev/null
  find . > $TEST_ARTIFACTS/actual.$old_layout
  popd >& /dev/null
  pushd $CURRENT_LAYOUT >& /dev/null
  find . > $TEST_ARTIFACTS/expected.$old_layout
  popd >& /dev/null
  check $old_layout
}

main() {
  initialize
  test_migration ws2
  test_migration ws1
  echo "$FAILURES failures: $0"
}

main
