#!/bin/bash

export NEWEST_LAYOUT=pt

export TEST_DIR=/home/jao/git/marcel/test/system/test_migration
export TEST_HOME=/tmp/test_home
export HOME=$TEST_HOME
export TEST_ARTIFACTS=/tmp/test_artifacts
export CURRENT_LAYOUT=$TEST_DIR/$NEWEST_LAYOUT
export XDG_CONFIG_HOME=$TEST_HOME/.config
export XDG_DATA_HOME=$TEST_HOME/.local/share

FAILURES=$((0))

initialize() {
  sudo rm -rf $TEST_ARTIFACTS
  mkdir -p $TEST_ARTIFACTS
}

check() {
  diff_file=$1"_to_"$NEWEST_LAYOUT".diff"
  diff $TEST_ARTIFACTS/expected.$1 $TEST_ARTIFACTS/actual.$1 > /$TEST_ARTIFACTS/$diff_file
  if [ $? != '0' ]; then
    FAILURES=$(($FAILURES+1))
    echo "Error on $diff_file"
  fi
}

run_migration() {
  old_layout=$1
  sudo rm -rf $TEST_HOME >& /dev/null
  cp -rp $TEST_DIR/$old_layout $TEST_HOME
  marcel <<EOF
  exit
EOF
  pushd $TEST_HOME >& /dev/null
  find . > $TEST_ARTIFACTS/actual.$old_layout
  popd >& /dev/null
  pushd $CURRENT_LAYOUT >& /dev/null
  find . > $TEST_ARTIFACTS/expected.$old_layout
  popd >& /dev/null
}

test_migration_ws3() {
  run_migration ws3
  check ws3
}

test_migration_ws2() {
  run_migration ws2
  check ws2
}

test_migration_ws1() {
  run_migration ws1
  check ws1
}

test_migration_xdg() {
  run_migration xdg
  # ws1 test data has a workspace named ws, which had no equivalent before ws1.
  grep -v "workspace/ws" $TEST_ARTIFACTS/expected.xdg > $TEST_ARTIFACTS/edited
  mv $TEST_ARTIFACTS/edited $TEST_ARTIFACTS/expected.xdg 
  check xdg
}

test_migration_original() {
  run_migration original
  # ws1 test data has a workspace named ws, which had no equivalent before ws1.
  grep -v "workspace/ws" $TEST_ARTIFACTS/expected.original > $TEST_ARTIFACTS/edited
  mv $TEST_ARTIFACTS/edited $TEST_ARTIFACTS/expected.original
  check original
}

main() {
  initialize
  test_migration_ws3
  test_migration_ws2
  test_migration_ws1
  test_migration_xdg
  test_migration_original
  echo "$FAILURES failures: $0"
}

main
